#!/bin/sh
#
# Copyright (c) 2016, Belkin Inc. All rights reserved.
#
# Publish "pre-setup" mesages to unconfigured Nodes.

# Set common values
source /etc/init.d/ulog_functions.sh
source /etc/init.d/sub_pub_funcs.sh

PROGNAME=$(basename $0)

usage() {
    printf "Usage:\n"
    printf "        %s {options}\n" $PROGNAME
    echo "Where {options} are one or more of:"
    printf "  -s {true/false} Start/Stop pre-setup\n"
    printf "  -h:         This help\n"
    printf "  -u {UUID}   UUID of Node to control\n"
}

while getopts ":dhs:u:" opt;do
    case $opt in
        d) DEBUG=1 ;;
        h) usage ; exit 0 ;;
        s) STATE=$OPTARG ;;
        u) UUID=$OPTARG ;;
        \?)
           echo "Invalid option: -$OPTARG" >&2
           usage
           exit 1
           ;;
        :)
           echo "Option -${OPTARG} needs an argument." >&2
           usage
           exit 1
           ;;
    esac
done
shift $((OPTIND-1))

validate UUID
validate STATE
case "$STATE" in
    true|TRUE|false|FALSE)
        # That's Good
    ;;
    *)
        echo "Bad argument (-s $STATE)"
        usage
        exit 1
        ;;
esac

PUB_TOPIC="$(omsg-conf -u pre_setup | sed "s/%uuid/$UUID/" )"
validate PUB_TOPIC

if [ $DEBUG ];then
    echo "$0 Options:"
    echo "   BIND_ADDR: '$BIND_ADDR'"
    echo "   HOST_PORT: '$HOST_PORT'"
    echo "   HOST_ADDR: '$HOST_ADDR'"
    echo "   TOPIC:     '$PUB_TOPIC'"
    echo "   UUID:      '$UUID'"
    echo "   STATE:     '$STATE'"
fi

# That's a lot of script for 1 line
echo $STATE | publish "$PUB_TOPIC"
