#!/bin/sh
#
# Copyright (c) 2019, Belkin Inc. All rights reserved.

# Set common values
source /etc/init.d/ulog_functions.sh
source /etc/init.d/sub_pub_funcs.sh

PROGNAME=$(basename $0)

EVENT_NAME=$1
EVENT_VALUE=$2

MODE=$(syscfg get smart_mode::mode)
UNCONFIGURED_MODE=0
MASTER_MODE=2
SLAVE_MODE=1
PUB_TOPIC="network/LRHK/update_violation"

if [ "$MODE" != "$SLAVE_MODE" ]; then
	echo "$PROGNAME: not in slave mode, exit"
	exit
fi

if [ $DEBUG ];then
    echo "Options:"
    echo "   BIND_ADDR: $BIND_ADDR"
    echo "   HOST_PORT: $HOST_PORT"
    echo "   HOST_ADDR: $HOST_ADDR"
    echo "   TOPIC    : $PUB_TOPIC"
    echo "   STATE    : $STATE"
fi

[ $DEBUG ] && echo "${PROG_NAME}: publishing lrhk::update_violation"

echo "$EVENT_VALUE" | publish "$PUB_TOPIC"
