#!/bin/sh
#
# Copyright (c) 2016, Belkin Inc. All rights reserved.
#
# Publish CONFIG-ME MQTT message
#
# To see the incoming data on the broker, use this command:
#   $ mosquitto_sub -t network/master/OMSG/cmd/CONFIG-ME -d
#

# Set common values
source /etc/init.d/ulog_functions.sh
source /etc/init.d/sub_pub_funcs.sh

PUB_TOPIC="$(omsg-conf -f /etc/subscriber.d/master.subs configure_me_done | sed "s/+/$TOPIC_UUID/" )"
validate PUB_TOPIC

if [ $DEBUG ];then
    echo "$0 Options:"
    echo "   BIND_ADDR: '$BIND_ADDR'"
    echo "   HOST_PORT: '$HOST_PORT'"
    echo "   HOST_ADDR: '$HOST_ADDR'"
    echo "   TOPIC:     '$PUB_TOPIC'"
fi

mk_infra_payload \
    -t status \
    -u "$(syscfg get device::uuid)" \
    -s "status:configured" | \
       publish "$PUB_TOPIC"
