#!/bin/sh
#
# Copyright (c) 2016, Belkin Inc. All rights reserved.
#
# Publish UPLOAD_SYSINFO MQTT message
#
# To see the incoming data on the broker, use this command:
#   $ mosquitto_sub -t network/slaves/OMSG/cmd/UPLOAD_SYSINFO -d
#

source /etc/init.d/ulog_functions.sh
source /etc/init.d/sub_pub_funcs.sh

if [ "$#" -lt 1 ]; then
    cat <<EOF
Error: missing argument
Usage: $(basename $0) <upload request uuid>
EOF
    exit 1
fi

UPLOAD_REQUEST_UUID=$1

PUB_TOPIC="$(omsg-conf -f /etc/subscriber.d/slave.subs UPLOAD_SYSINFO | sed "s/+/$TOPIC_UUID/" )"
validate PUB_TOPIC

if [ $DEBUG ];then
    echo "$0 Options:"
    echo "   BIND_ADDR: '$BIND_ADDR'"
    echo "   HOST_PORT: '$HOST_PORT'"
    echo "   HOST_ADDR: '$HOST_ADDR'"
    echo "   TOPIC:     '$PUB_TOPIC'"
fi

echo "Sending UUID $UPLOAD_REQUEST_UUID to $PUB_TOPIC" > /dev/console
echo "$UPLOAD_REQUEST_UUID" | publish "$PUB_TOPIC" 
