#!/bin/sh
#
# Copyright (c) 2016, Belkin Inc. All rights reserved.
#
# Publish nodes 11v steering command to an MQTT topic
#
# To see the incoming data on the broker, use this command:
#   $ mosquitto_sub -t /network/+/BH/status -d
#
DEBUG=0


# Set common values
source /etc/init.d/sub_pub_funcs.sh

usage()
{
    echo "$0 [client_mac] [duration] [action] [exclude]" > /dev/console
    exit 1
}
PUB_TOPIC="$(omsg-conf -f /etc/subscriber.d/slave.subs NODES_TEMPORARY_BLACKLIST)"

if [ -z "$PUB_TOPIC" ]; then
    PUB_TOPIC="network/master/cmd/nodes_temporary_blacklist"
fi

validate PUB_TOPIC


if [ "$DEBUG" = "1" ];then
    echo "Options:"
    echo "   BIND_ADDR: $BIND_ADDR"
    echo "   HOST_PORT: $HOST_PORT"
    echo "   HOST_ADDR: $HOST_ADDR"
    echo "   TOPIC    : $PUB_TOPIC"
    echo "   STATUS   : $STATUS"
fi

CLNT="$1"
DURATION="$2"
ACTION="$3"
EXCLUDE_NODES="$4"

[ -z "$CLNT" -o -z "$DURATION" -o -z "$ACTION" ] && usage

mk_infra_payload -s "client:$CLNT" -s "duration:$DURATION" -s "action:$ACTION" \
    -r "exclude:$(jsongen -o a -a \"$EXCLUDE_NODES\")" | publish "$PUB_TOPIC"
exit 0
