#!/bin/sh

#------------------------------------------------------------------
# © 2016 Belkin International, Inc. and/or its affiliates. All rights reserved.
#------------------------------------------------------------------

source /etc/init.d/service_registration_functions.sh

##################################################################
# Name of this service
# --------------------
# You MUST set this to a globally unique string
##################################################################

# Enter service name below
SERVICE_NAME="tesseract"


##################################################################
# Name of the default handler
# ---------------------------
# Name of the handler to invoke upon default events [start|stop|restart]
# If the value is set to NULL, then no default events will be installed
#
# It is your responsibility to ensure that the default handler code
# exists.
#
# Note
#  When the handler is called, the 1st parameter ($1) will be the event name
#  and the 2nd parameter ($2) will be the event value (or NULL if no value) when the event occurred
#  and subsequent parameters if any are defined as extra parameters as described below
##################################################################

SERVICE_DEFAULT_HANDLER="/etc/init.d/service_${SERVICE_NAME}.sh"

##################################################################
# Custom Events
# -------------
# If the service should receive events other than start stop restart, then
# declare them. If there are no custom events then set to NULL
#
# The format of each line of a custom event string is:
# name_of_event | path/filename_of_handler | activation_flags or NULL | tuple_flags or NULL | extra parameters
#
# Each line must be separated from the next with a ';'
# The last line does not need a separator
#
# Example of a custom event string containing several events
#
# SERVICE_CUSTOM_EVENTS="\
#              foo|$SERVICE_DEFAULT_HANDLER|NULL|NULL|\$wan_proto @ipv4_wan_ipaddr; \
#              bar|/etc/init.d/barhandler.sh|$ACTION_FLAG_NOT_THREADSAFE; \
#              fubar|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT \
#             "
# (see lego_overlay/proprietary/init/init.d/service_registration_functions.sh for
#  an explanation of the format of each event)
##################################################################

# EXAMPLE: on lan and wan network restart
# SERVICE_CUSTOM_EVENTS="\
#                         wan-started|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
#                         lan-started|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT \
#                       "


CLIENT_STEER_REPORT_EVNAME="$(omsg-conf -s --attribute=event TESSERACT_CLIENT_STEER_FSM_REPORT)"

SERVICE_CUSTOM_EVENTS="\
                        devinfo|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        mqttsub::wlansubdev|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        slave_offline|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        subscriber::connected|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_NORMAL; \
                        $CLIENT_STEER_REPORT_EVNAME|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        wlan::send-client-survey|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        wifi_client_site_survey|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        wlan::client-survey|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        wlan::nodes_steering_start|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        wlan::node-survey|$SERVICE_DEFAULT_HANDLER|$ACTION_FLAG_NOT_THREADSAFE|$TUPLE_FLAG_EVENT; \
                        wlan::nodes_temporary_blacklist|$SERVICE_DEFAULT_HANDLER|$ACTION_FLAG_NOT_THREADSAFE|$TUPLE_FLAG_EVENT; \
                        wlan::reconsider-backhaul|$SERVICE_DEFAULT_HANDLER|$ACTION_FLAG_NOT_THREADSAFE|$TUPLE_FLAG_EVENT; \
                        wlan::report-neighbors|$SERVICE_DEFAULT_HANDLER|$ACTION_FLAG_NOT_THREADSAFE|$TUPLE_FLAG_EVENT; \
                        wifi-status|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                        report_nb_rssi|$SERVICE_DEFAULT_HANDLER|NULL|$TUPLE_FLAG_EVENT; \
                      "

#######################################################################
#             NOTHING MORE TO DO
# In general there is no need to change anything below
#######################################################################

# ------------------------------------------------------------------------------------
# function do_stop
# ------------------------------------------------------------------------------------
do_stop() {
   /etc/init.d/pmon.sh unregister ${SERVICE_NAME}
   sm_unregister $SERVICE_NAME
}

# ------------------------------------------------------------------------------------
# function do_start
# ------------------------------------------------------------------------------------
do_start () {
   sm_register $SERVICE_NAME $SERVICE_DEFAULT_HANDLER "$SERVICE_CUSTOM_EVENTS"
   /etc/init.d/pmon.sh register ${SERVICE_NAME}
}

#-----------------------------------------------------------------------------------
# This script is in the registration directory and will be called automatically at
# system boot. This allows the service to register for events of interest, and to
# set the service status.
#
# It could also be called during running system explicitly
#-----------------------------------------------------------------------------------
case "$1" in
   start|"")
      do_start
      ;;
   restart|reload|force-reload)
      do_stop
      do_start
      ;;
   stop)
      do_stop
      ;;

   *)
      echo "Usage: $SERVICE_NAME [start|stop|restart]" >&2
      exit 3
      ;;
esac
